// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWocfpyx647ogpTp51f_ZQUzBhr6WBlSU',
    appId: '1:19198108932:web:447924d1aecc8b417a1c51',
    messagingSenderId: '19198108932',
    projectId: 'library-app-2485f',
    authDomain: 'library-app-2485f.firebaseapp.com',
    databaseURL: 'https://library-app-2485f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'library-app-2485f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCngOy8kGRIKFIrbzo7Z2jDcSdNLDKMQ8k',
    appId: '1:19198108932:android:498a3f4651811e887a1c51',
    messagingSenderId: '19198108932',
    projectId: 'library-app-2485f',
    databaseURL: 'https://library-app-2485f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'library-app-2485f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9uaV383DKXUyhtDXmPwDd7bOhWYSvqPw',
    appId: '1:19198108932:ios:ab7fed2eb933d3877a1c51',
    messagingSenderId: '19198108932',
    projectId: 'library-app-2485f',
    databaseURL: 'https://library-app-2485f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'library-app-2485f.appspot.com',
    iosBundleId: 'com.example.libraryApp',
  );
}
